### ISSUE TITLE
Problem with Kibana 6.7.x

### ISSUE THREAD

**Issue by GustavoBellini** [nreese/kibana-time-plugin#54]
Hello everyone,

the plugin is not working with Kibana version 6.7.1 and 6.7.

The error below is shown:

@import (reference) "~ui/styles/mixins.less";
 ^
Can't resolve 'ui/styles/mixins.less' in '/usr/share/kibana/plugins/kibana-time-plugin/public'
in /usr/share/kibana/plugins/kibana-time-plugin/public/time.less (line 1, column 0)
at runLoaders (/usr/share/kibana/node_modules/webpack/lib/NormalModule.js:286:20)
at /usr/share/kibana/node_modules/loader-runner/lib/LoaderRunner.js:364:11
at /usr/share/kibana/node_modules/loader-runner/lib/LoaderRunner.js:230:18
at context.callback (/usr/share/kibana/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at process._tickCallback (internal/process/next_tick.js:68:7)

I managed to fix it change the time.less file and updating the first line by @import "/usr/share/kibana/src/ui/public/styles/bootstrapmixins.less";

But now the error below appears:

.visualization-options {
.flex-parent();
^
.flex-parent is undefined
in /usr/share/kibana/plugins/kibana-time-plugin/public/time.less (line 15, column 6)
at runLoaders (/usr/share/kibana/node_modules/webpack/lib/NormalModule.js:286:20)
at /usr/share/kibana/node_modules/loader-runner/lib/LoaderRunner.js:364:11
at /usr/share/kibana/node_modules/loader-runner/lib/LoaderRunner.js:230:18
at context.callback (/usr/share/kibana/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at process._tickCallback (internal/process/next_tick.js:68:7)

Can someone help me?

Thanks.

**Comment by RobinELM** [comment]
Hello,

I encountered the same issue, apparently this is linked to the move from LESS to SASS implemented in 6.7 ( https://github.com/elastic/kibana/pull/23413 ).
The ui/style/mixin.less has been replaced by _mixins.scss , I am not familiar with LESS / SASS and their processing. I tried to import the .scss instead of the .less file but the plugin is missing the right component to integrate it. It might require to move the whole plugin style to SASS as I am not sure if we can mix both =/

**Comment by conmurray** [comment]
Thanks @RobinELM  for that info. I had checked recently as well and encountered the same issue.
Is moving to SASS a big job?

**Comment by holgerbrandl** [comment]
Same problem with v7.0

**Comment by andresbrandworkz** [comment]
Hello, 

I also found the same issue with Kibana 7.0.0.
Any plans on adapting this plugin for the latest version?

```
 FATAL  Error: Optimizations failure.
   5643 modules
    
    ERROR in ./plugins/kibana-time-plugin/public/time.less
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    
    
    @import (reference) "~ui/styles/mixins.less";
    ^
    Can't resolve 'ui/styles/mixins.less' in '/home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/plugins/kibana-time-plugin/public'
          in /home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/plugins/kibana-time-plugin/public/time.less (line 1, column 0)
        at runLoaders (/home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/node_modules/webpack/lib/NormalModule.js:286:20)
        at /home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at context.callback (/home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    
    ERROR in ./plugins/kibana-time-plugin/public/timeController.js
    Module not found: Error: Can't resolve 'ui/timepicker/time_units' in '/home/andres/Apps/Elastic/Kibana/kibana-7.0.0-linux-x86_64/plugins/kibana-time-plugin/public'
```

Thanks.

**Comment by andresbrandworkz** [comment]
Hello everybody, 

I got the plugin working on Kibana v7.0.1 with some small modifications.

![Screenshot from 2019-05-02 16-40-03](https://user-images.githubusercontent.com/25618087/57083603-1ebefb80-6cf9-11e9-9846-92361a5d2fd1.png)

`time.less`
I changed the path to the mixins.less file. It seems they've placed a legacy folder aside with old files.
```
@import (reference) "../../../src/legacy/ui/public/styles/bootstrap/mixins.less";
```
Also, I removed two occurrences of `.flex-parent();` because it was making the plugin not compile.
(Not sure why those were needed before, though).


`timeController.js`
time_units is no longer available. So I removed the import and assigned the constant directly.
```
// ...
  $scope.units = {
    s: 'second',
    m: 'minute',
    h: 'hour',
    d: 'day',
    w: 'week',
    M: 'month',
    y: 'year'
  };
// ...
```

It seems to be working, and even synchronising with the new super date picker Kibana is using now.
But can anyone advise about how dodgy this workaround is, please?

Thanks.

**Comment by nreese** [comment]
Looks good. Would you mind putting together a PR?

**Comment by andresbrandworkz** [comment]
Hello,
I have just done it.
https://github.com/nreese/kibana-time-plugin/pull/55

**Comment by SiwyDym** [comment]
Fix in [PR](https://github.com/nreese/kibana-time-plugin/pull/56)

**Comment by nreese** [comment]
closed by https://github.com/nreese/kibana-time-plugin/pull/56
